# Generated by Django 3.0.2 on 2020-06-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_by', models.CharField(max_length=10)),
                ('sent_to', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
            ],
        ),
    ]
