# Generated by Django 3.0.2 on 2020-06-18 09:11

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocations',
            name='police_allotted',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=147, size=7),
        ),
    ]
